window.galdata = {}
galdata['100PStArea1'] = {
    'swfName':"StackedArea2D",
    'data': "<chart caption=\'Visits from search engines\' showValues=\'0\' plotGradientColor=\'999999\' plotFillAlpha=\'95\' plotBorderColor=\'FFFFFF\'  formatNumberScale=\'0\' stack100Percent=\'1\' showPercentValues=\'1\' bgColor=\"000000\" borderColor=\"FF00000\" bgAlpha=\"100\">	<categories>		<category label=\'Jan\' />		<category label=\'Feb\' />		<category label=\'Mar\' />		<category label=\'Apr\' />		<category label=\'May\' />		<category label=\'Jun\' />		<category label=\'Jul\' />		<category label=\'Aug\' />		<category label=\'Sep\' />		<category label=\'Oct\' />		<category label=\'Nov\' />		<category label=\'Dec\' />	</categories>	<dataset seriesName=\'Google\'>		<set value=\'5040\' />		<set value=\'4794\' />		<set value=\'5026\' />		<set value=\'5341\' />		<set value=\'4800\' />		<set value=\'4507\' />		<set value=\'5701\' />		<set value=\'4671\' />		<set value=\'4980\' />		<set value=\'4041\' />		<set value=\'3813\' />		<set value=\'3691\' />	</dataset>	<dataset seriesName=\'Yahoo\'>		<set value=\'1200\' />		<set value=\'1124\' />		<set value=\'1006\' />		<set value=\'921\' />		<set value=\'1500\' />		<set value=\'1007\' />		<set value=\'921\' />		<set value=\'971\' />		<set value=\'1080\' />		<set value=\'1041\' />		<set value=\'1113\' />		<set value=\'1091\' />	</dataset>	<dataset seriesName=\'MSN\'>		<set value=\'400\' />		<set value=\'524\' />		<set value=\'606\' />		<set value=\'421\' />		<set value=\'500\' />		<set value=\'707\' />		<set value=\'621\' />		<set value=\'471\' />		<set value=\'680\' />		<set value=\'441\' />		<set value=\'713\' />		<set value=\'491\' />	</dataset>	<dataset seriesName=\'Others\'>		<set value=\'765\' />		<set value=\'571\' />		<set value=\'532\' />		<set value=\'411\' />		<set value=\'500\' />		<set value=\'407\' />		<set value=\'421\' />		<set value=\'551\' />		<set value=\'600\' />		<set value=\'541\' />		<set value=\'613\' />		<set value=\'591\' />	</dataset></chart>"
};
galdata['100PStBar2D1'] = {
    'swfName':"StackedBar2D",
    'data': "<chart palette=\'2\' caption=\'Monthly Sales Summary\' subcaption=\"100% composition and comparison\"  xAxisName=\'Month\' yAxisName=\'Sales\' numberPrefix=\'$\' showValues=\'0\' stack100Percent=\'1\' showPercentValues=\'1\'><categories>	<category label=\'Jan\' />	<category label=\'Feb\' />	<category label=\'Mar\' />	<category label=\'Apr\' />	<category label=\'May\' />	<category label=\'Jun\' />	<category label=\'Jul\' />	<category label=\'Aug\' />	<category label=\'Sep\' />	<category label=\'Oct\' />	<category label=\'Nov\' />	<category label=\'Dec\' /></categories><dataset seriesName=\'Product A\' color=\'B1D1DC\' >	<set value=\'27400\' />	<set value=\'29800\'/>	<set value=\'25800\' />	<set value=\'26800\' />	<set value=\'29600\' />	<set value=\'32600\' />	<set value=\'31800\' />	<set value=\'36700\' />	<set value=\'29700\' />	<set value=\'31900\' />	<set value=\'32900\' />	<set value=\'34800\' /></dataset><dataset seriesName=\'Product B\' color=\'C8A1D1\' >	<set value=\'5400\' />	<set value=\'9800\' />	<set value=\'4500\'/>	<set value=\'6500\'/>	<set value=\'7600\' />	<set value=\'6800\' />	<set value=\'11800\' />	<set value=\'19700\' />	<set value=\'21700\' />	<set value=\'21900\' />	<set value=\'22900\' />	<set value=\'29800\' /></dataset></chart> "
};
